<script setup>
import { ref, reactive, computed, watch, onMounted, onUnmounted, toRaw, nextTick } from 'vue';
import { LayoutDashboard, Boxes, Route, Users, Building2, MapPin, ShieldBan, ChartNoAxesCombined, Bell, Search, Plus, ArrowUpRight, ArrowRight, ChevronRight, ChevronDown, LogOut, Menu, X, Ship, Anchor, Globe2, Package, Clock3, Check, CheckCheck, CircleCheck, CircleAlert, Download, SlidersHorizontal, Eye, Pencil, Mail, LockKeyhole, ArrowLeft, RefreshCw, MoreHorizontal, Truck, FileText, UserPlus, Settings2, CalendarDays, MapPinned, Send, ShieldCheck } from 'lucide-vue-next';
import { initialData, demoAccounts, statuses, visibleContainers, visibleSuppliers, canBook, isOverdue, containerNumberIssue } from './data';
import ThemeToggle from './ThemeToggle.vue';

const theme = ref(document.documentElement.dataset.theme || 'dark');
watch(theme, value => {
  document.documentElement.dataset.theme = value;
  try { localStorage.setItem('kodiak-theme', value); } catch {}
});

const STORE = 'kodiak-demo-v1';
const SESSION = 'kodiak-demo-session';
function restore() { try { const saved = JSON.parse(localStorage.getItem(STORE)); if (saved?.containers && saved?.users && saved?.ports) return saved; } catch {} return initialData(); }
const data = reactive(restore());
const userId = ref(sessionStorage.getItem(SESSION) || '');
const user = computed(() => data.users.find(u => u.id === userId.value && u.active));
const page = ref('dashboard');
const selectedId = ref('');
const mobileNav = ref(false);
const search = ref('');
const statusFilter = ref('All statuses');
const supplierFilter = ref('');
const report = ref('register');
const locationTab = ref('ports');
const login = reactive({ email: '', password: '' });
const loginError = ref('');
const modal = ref('');
const form = ref({});
const formError = ref('');
const toast = ref('');
let toastTimer;
const persistenceError = ref(false);
let priorFocus;
watch(modal, async value => {
  document.body.style.overflow=value?'hidden':'';
  if(value){priorFocus=document.activeElement;await nextTick();document.querySelector('.modal input:not([disabled]), .modal select, .modal textarea, .modal button')?.focus();}
  else {await nextTick();priorFocus?.focus?.();}
});
watch(data, () => { try { localStorage.setItem(STORE, JSON.stringify(data)); persistenceError.value = false; } catch { persistenceError.value = true; } }, { deep: true });
watch(userId, id => { if(id) sessionStorage.setItem(SESSION,id); else sessionStorage.removeItem(SESSION); });
const scoped = computed(() => visibleContainers(data, user.value));
const suppliers = computed(() => visibleSuppliers(data,user.value));
const orgName = computed(() => user.value?.role === 'admin' ? 'Kodiak operations' : (user.value?.role === 'supplier' ? data.suppliers : data.distributors).find(o => o.id === user.value?.org)?.name || '');
const currentSupplier = computed(() => data.suppliers.find(s=>s.id === user.value?.org));
const isAdmin = computed(()=> user.value?.role === 'admin');
const canCreate = computed(()=>isAdmin.value || (user.value?.role === 'supplier' && canBook(data,user.value.org)));
const detail = computed(()=>scoped.value.find(c=>c.id === selectedId.value));
const metrics = computed(()=>({total:scoped.value.length, transit:scoped.value.filter(c=>c.status==='In transit').length, delivered:scoped.value.filter(c=>c.status==='Delivered').length, hold:scoped.value.filter(c=>c.hold).length, overdue:scoped.value.filter(c=>isOverdue(c)).length}));
const filtered = computed(()=>scoped.value.filter(c=>{
  const q=search.value.toLowerCase();
  return (!q || [c.number,c.id,supplierName(c.supplierId),port(c.origin).name,port(c.destination).name,c.cargo].some(x=>x?.toLowerCase().includes(q))) && (statusFilter.value==='All statuses' || (statusFilter.value==='On hold'?c.hold:c.status===statusFilter.value)) && (!supplierFilter.value||c.supplierId===supplierFilter.value);
}));
const navItems = computed(()=>[
  { id:'dashboard', label:'Overview', icon:LayoutDashboard },
  { id:'containers', label:'Containers', icon:Boxes, count:scoped.value.length },
  { id:'tracking', label:'Tracking', icon:Route },
  ...(user.value?.role!=='supplier'?[{id:'suppliers',label:isAdmin.value?'Suppliers':'My suppliers',icon:Users}]:[]),
  ...(isAdmin.value?[{id:'distributors',label:'Distributors',icon:Building2},{id:'users',label:'User management',icon:UserPlus}]:[]),
  {id:'reports',label:'Reports & insights',icon:ChartNoAxesCombined},
]);
const notifications = computed(()=>data.notifications.filter(n=>n.containerId ? scoped.value.some(c=>c.id===n.containerId) : isAdmin.value || n.supplierId === user.value?.org));
const unread = computed(()=>notifications.value.filter(n=>!n.readBy.includes(userId.value)).length);
const pageTitle = computed(()=>({dashboard:'Overview', containers:'Containers',tracking:'Shipment tracking',detail:'Container details', suppliers:isAdmin.value?'Suppliers':'My suppliers',distributors:'Distributors',users:'User management',locations:'Location directory',blacklist:'Restrictions & blacklist',reports:'Reports & insights',notifications:'Notification center'}[page.value]));
const routeGroups = computed(()=>{const groups={}; scoped.value.forEach(c=>{const key=c.origin+'|'+c.destination; if(!groups[key])groups[key]={origin:c.origin,destination:c.destination,total:0,active:0,delivered:0,hold:0};const g=groups[key];g.total++;g.active+=c.status!=='Delivered'?1:0;g.delivered+=c.status==='Delivered'?1:0;g.hold+=c.hold?1:0;});return Object.values(groups).sort((a,b)=>b.total-a.total);});
const activity = computed(()=>scoped.value.flatMap(c=>c.events.map(e=>({...e,container:c}))).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4));
const attention = computed(()=>scoped.value.filter(c=>c.hold||isOverdue(c)||c.status==='Booked'));
const restricted = computed(()=>data.suppliers.filter(s=>s.state==='Blacklisted'));
const modalTitle = computed(()=>({container:'Register a container',supplier:'Register a supplier',distributor:'Register a distributor',user:'Create a user',update:'Update container tracking',restrict:'Blacklist supplier',release:'Remove supplier restriction',approve:'Approve supplier',country:'Add a country',state:'Add a state',port:'Add a port',reset:'Reset demo data'}[modal.value]));
const stateOptions = computed(()=>data.states.filter(s=>s.countryId===form.value.countryId));
function port(id){return data.ports.find(p=>p.id===id)||{name:'Not assigned',city:'—',code:'—',countryId:''};}
function countryName(id){return data.countries.find(c=>c.id===id)?.name || id;}
function supplierName(id){return data.suppliers.find(s=>s.id===id)?.name || 'Unknown supplier';}
function distributorName(id){return data.distributors.find(d=>d.id===id)?.name || 'Pending assignment';}
function initials(name=''){return name.split(' ').slice(0,2).map(s=>s[0]).join('');}
function date(value, full=false){if(!value)return 'Not set';return new Date(value.length===10?value+'T12:00:00':value).toLocaleDateString('en-GB',{day:'2-digit',month:'short',...(full?{year:'numeric'}:{})});}
function time(value){return new Date(value).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});}
function tone(status){return ({'In transit':'blue','Delivered':'green','At origin':'amber','At destination':'purple','Booked':'gray','Active':'green','Pending':'amber','Blacklisted':'red'}[status]||'gray');}
function notify(message){toast.value=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',4500);}
function go(id){page.value=id; search.value='';statusFilter.value='All statuses';supplierFilter.value='';mobileNav.value=false;window.scrollTo({top:0});}
function openDetail(c){selectedId.value=c.id;go('detail');}
function signIn(){const u=data.users.find(u=>u.email.toLowerCase()===login.email.trim().toLowerCase()&&u.password===login.password&&u.active);if(!u){loginError.value='Email or password is incorrect, or this account is inactive.';return;}userId.value=u.id;loginError.value='';go('dashboard');}
function demoLogin(role){const account=demoAccounts.find(a=>a.role===role);login.email=account.email;login.password=account.password;signIn();}
function logout(){userId.value='';modal.value='';login.password='';loginError.value='';}
function openModal(type,entity){
  modal.value=type;formError.value='';
  form.value={};
  if(type==='container')form.value={supplierId:user.value?.role==='supplier'?user.value.org:data.suppliers.find(s=>s.state==='Active')?.id,number:'',type:'40′ High Cube',origin:'INNSA',destination:'AEJEA',cargo:'',weight:'',packages:'',departure:'',eta:'',reference:'',vessel:''};
  if(type==='supplier')form.value={name:'',contact:'',email:'',phone:'',country:'India',distributorId:isAdmin.value?'d1':'',category:'General cargo',address:'',password:''};
  if(type==='distributor')form.value={name:'',contact:'',email:'',phone:'',country:'United Arab Emirates',address:''};
  if(type==='user')form.value={name:'',email:'',password:'',role:'supplier',org:'s1'};
  if(type==='update')form.value={...structuredClone(toRaw(entity)),eventDate:localDateTime(),note:'',location:entity.events.at(-1)?.location||port(entity.origin).name};
  if(['restrict','release','approve'].includes(type))form.value={id:entity.id,name:entity.name,reason:'',distributorId:entity.distributorId||'d1'};
  if(type==='country')form.value={name:'',code:''};
  if(type==='state')form.value={name:'',countryId:'IN'};
  if(type==='port')form.value={name:'',code:'',city:'',countryId:'IN',stateId:'MH'};
}
function localDateTime(){const d=new Date(); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,5);}
function log(action,entity,reason){data.audit.unshift({id:uid('a'),action,entity,reason,by:user.value?.name||'Self registration',date:new Date().toISOString()});}
function addNotification(title,text,containerId,supplierId){data.notifications.unshift({id:uid('n'),title,text,containerId,supplierId,date:new Date().toISOString(),readBy:[]});}
function save(){
  const f=form.value;formError.value='';
  const fail=m=>{formError.value=m;};
  const adminOnly=['distributor','user','update','restrict','release','approve','country','state','port'];
  if(adminOnly.includes(modal.value)&&!isAdmin.value)return fail('Only Kodiak administrators can perform this action.');
  if(modal.value==='container'){
    if(!canCreate.value || !canBook(data,f.supplierId) || (user.value.role==='supplier'&&f.supplierId!==user.value.org))return fail('Only approved, active suppliers can register containers.');
    if(f.origin===f.destination)return fail('Choose a different destination port.');
    if(f.eta<f.departure)return fail('Expected arrival must be on or after departure.');
    const numberIssue=containerNumberIssue(data,f.number);if(numberIssue)return fail(numberIssue);
    const n=Math.max(2048,...data.containers.map(c=>Number(c.id.split('-')[1])||0))+1;
    const c={...f,id:'KD-'+n,number:f.number.trim().toUpperCase()||'Pending allocation',distributorId:data.suppliers.find(s=>s.id===f.supplierId).distributorId,status:'Booked',hold:false,blacklisted:false,created:new Date().toISOString().slice(0,10),events:[{status:'Booked',date:localDateTime(),location:port(f.origin).name,note:'Container registration submitted. Awaiting Kodiak review and allocation.',by:user.value.name,recordedAt:new Date().toISOString()}]};
    data.containers.unshift(c);log('Container registered',c.id,'Supplier booking');addNotification('New container registration',supplierName(c.supplierId)+' submitted '+c.id+'.',c.id);modal.value='';openDetail(c);notify('Container '+c.id+' registered successfully.');return;
  }
  if(modal.value==='supplier'){
    if(data.suppliers.some(s=>s.email.toLowerCase()===f.email.toLowerCase())||data.users.some(u=>u.email.toLowerCase()===f.email.toLowerCase()))return fail('This email is already registered.');
    const id=uid('s');const {password,...profile}=f;
    data.suppliers.push({...profile,id,state:isAdmin.value?'Active':'Pending',reason:''});
    if(password)data.users.push({id:uid('u'),name:f.contact,email:f.email,password,role:'supplier',org:id,active:true});
    log('Supplier registered',id,isAdmin.value?'Admin-created':'Pending approval');addNotification('Supplier application received',f.name+' is awaiting account review.',null,id);
    modal.value='';notify(isAdmin.value?'Supplier created.':'Registration submitted. You can sign in to view your pending account.');return;
  }
  if(modal.value==='distributor'){
    if(data.distributors.some(d=>d.email.toLowerCase()===f.email.toLowerCase()))return fail('A distributor with this email already exists.');
    data.distributors.push({...f,id:uid('d'),active:true});log('Distributor created',f.name,'');
  }
  if(modal.value==='user'){
    if(data.users.some(u=>u.email.toLowerCase()===f.email.toLowerCase()))return fail('A user with this email already exists.');
    data.users.push({...f,id:uid('u'),org:f.role==='admin'?'kodiak':f.org,active:true});log('User created',f.email,f.role);
  }
  if(modal.value==='update'){
    const c=data.containers.find(c=>c.id===f.id);if(!c)return fail('Container no longer exists.');
    if(['In transit','At destination','Delivered'].includes(f.status)&&(!f.number.trim()||f.number==='Pending allocation'))return fail('Assign a physical container number before dispatch.');
    if(f.status==='Delivered'&&f.hold)return fail('Release the hold before marking this container delivered.');
    if(f.eta&&f.departure&&f.eta<f.departure)return fail('Arrival must be on or after departure.');
    if(!f.note.trim())return fail('Add an operational note explaining this update.');
    if(f.hold&&!f.holdReason?.trim())return fail('Enter a reason for the hold.');
    if(f.blacklisted&&!f.blacklistReason?.trim())return fail('Enter a reason for the container restriction.');
    if(new Date(f.eventDate)>new Date())return fail('A recorded event cannot be in the future.');
    if(f.eventDate<c.events[c.events.length-1].date)return fail('For this prototype, enter an event after the latest timeline entry.');
    const numberIssue=containerNumberIssue(data,f.number,c.id);if(numberIssue)return fail(numberIssue);
    const previous=c.status;const restrictionChanged=c.hold!==f.hold||c.blacklisted!==f.blacklisted;
    Object.assign(c,{number:f.number.toUpperCase(),status:f.status,eta:f.eta,vessel:f.vessel,hold:f.hold,holdReason:f.hold?f.holdReason:'',blacklisted:f.blacklisted,blacklistReason:f.blacklisted?f.blacklistReason:''});
    c.events.push({status:f.status,date:f.eventDate,location:f.location,note:f.note,by:user.value.name,recordedAt:new Date().toISOString(),hold:f.hold,restrictionChanged});
    log('Tracking updated',c.id,previous+' → '+f.status+' · '+f.note);addNotification(restrictionChanged?'Container restriction updated':'Tracking updated',c.id+' · '+f.status,c.id);
  }
  if(['restrict','release','approve'].includes(modal.value)){
    const s=data.suppliers.find(s=>s.id===f.id);const action=modal.value;
    if(action==='approve'){s.state='Active';s.distributorId=f.distributorId;}
    else {s.state=action==='restrict'?'Blacklisted':'Active';s.reason=action==='restrict'?f.reason:'';s.restrictedAt=new Date().toISOString();s.restrictedBy=user.value.name;}
    log(action==='approve'?'Supplier approved':action==='restrict'?'Supplier blacklisted':'Supplier restriction removed',s.name,f.reason||'Distributor assigned');addNotification('Supplier account updated',s.name+' · '+s.state,null,s.id);
  }
  if(modal.value==='country'){
    if(data.countries.some(c=>c.code===f.code.toUpperCase()||c.name.toLowerCase()===f.name.toLowerCase()))return fail('This country is already in the directory.');
    data.countries.push({id:f.code.toUpperCase(),code:f.code.toUpperCase(),name:f.name});
  }
  if(modal.value==='state'){
    if(data.states.some(s=>s.countryId===f.countryId&&s.name.toLowerCase()===f.name.toLowerCase()))return fail('This state already exists in that country.');
    data.states.push({...f,id:uid('state')});
  }
  if(modal.value==='port'){
    if(data.ports.some(p=>p.code===f.code.toUpperCase()))return fail('This port code already exists.');
    if(!data.states.some(s=>s.id===f.stateId&&s.countryId===f.countryId))return fail('Select a state belonging to this country.');
    data.ports.push({...f,id:f.code.toUpperCase(),code:f.code.toUpperCase()});
  }
  modal.value='';notify('Changes saved successfully.');
}
function markRead(n){if(!n.readBy.includes(userId.value))n.readBy.push(userId.value);if(n.containerId){const c=scoped.value.find(c=>c.id===n.containerId);if(c)openDetail(c);}}
function markAll(){notifications.value.forEach(n=>{if(!n.readBy.includes(userId.value))n.readBy.push(userId.value);});notify('All notifications marked as read.');}
function exportCSV(){
  let rows;
  if(report.value==='routes'&&page.value==='reports')rows=[['Origin','Destination','Total journeys','Active','Delivered','On hold'],...routeGroups.value.map(g=>[port(g.origin).name,port(g.destination).name,g.total,g.active,g.delivered,g.hold])];
  else if(report.value==='suppliers'&&page.value==='reports')rows=[['Supplier','Account state','Journeys','In transit','Delivered','On hold'],...suppliers.value.map(s=>{const list=scoped.value.filter(c=>c.supplierId===s.id);return [s.name,s.state,list.length,list.filter(c=>c.status==='In transit').length,list.filter(c=>c.status==='Delivered').length,list.filter(c=>c.hold).length];})];
  else rows=[['Booking','Container','Supplier','Origin','Destination','Status','On hold','Expected arrival'],...filtered.value.map(c=>[c.id,c.number,supplierName(c.supplierId),port(c.origin).name,port(c.destination).name,c.status,c.hold?'Yes':'No',c.eta])];
  const csv=rows.map(r=>r.map(v=>'"'+String(/^[=+@-]/.test(String(v))?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='kodiak-'+(page.value==='reports'?report.value:'containers')+'.csv';a.click();URL.revokeObjectURL(url);notify('Report exported as CSV.');
}
function reset(){Object.assign(data,initialData());userId.value='';modal.value='';go('dashboard');notify('Demo restored. All sample accounts are ready.');}
function escape(e){if(e.key==='Escape'){modal.value='';mobileNav.value=false;}if(e.key==='Tab'&&modal.value){const items=[...document.querySelectorAll('.modal button,.modal input,.modal select,.modal textarea')].filter(el=>!el.disabled&&el.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
onMounted(()=>window.addEventListener('keydown',escape));onUnmounted(()=>{window.removeEventListener('keydown',escape);clearTimeout(toastTimer);});
</script>

<template>
  <div v-if="!user" class="login-page">
    <section class="login-story">
      <a class="brand login-brand" href="#"><span class="brand-mark"><Boxes :size="25" /></span><span>kodiak<span class="brand-dot">.</span></span></a>
      <div class="story-copy"><div class="eyebrow light"><span class="live-dot"></span> CONNECTED CONTAINER OPERATIONS</div><h1>Every container.<br>Every milestone.<br><span>One clear view.</span></h1><p>Bring your suppliers, distributors, and global shipments together. A simpler way to keep business moving.</p></div>
      <div class="login-route"><div class="route-location"><span class="country-code">IN</span><div><small>ORIGIN</small><strong>Nhava Sheva</strong><span>Mumbai, India</span></div></div><div class="route-line"><span></span><Ship :size="25"/><span></span></div><div class="route-location"><span class="country-code">AE</span><div><small>DESTINATION</small><strong>Jebel Ali</strong><span>Dubai, UAE</span></div></div><div class="floating-cargo"><Package :size="18"/><span>MSCU 782341-6</span><span class="mini-dot"></span> In transit</div></div>
      <div class="story-bottom"><span><ShieldCheck :size="16"/> Clear roles. Connected teams.</span><span>KODIAK LOGISTICS</span></div>
      <div class="container-art" aria-hidden="true"><div></div><div></div><div></div></div>
    </section>
    <section class="login-panel"><div class="login-top"><ThemeToggle v-model="theme"/><span class="demo-pill"><span></span> INTERACTIVE PROTOTYPE</span></div><div class="login-content"><div class="welcome-icon"><Truck :size="24"/></div><h2>Kodiak Tracking</h2><p class="muted">Sign in to your account</p>
      <form @submit.prevent="signIn" class="login-form"><label>Email address<div class="input-icon"><Mail :size="17"/><input v-model="login.email" type="email" placeholder="you@company.com" autocomplete="username" required /></div></label><label>Password<div class="input-icon"><LockKeyhole :size="17"/><input v-model="login.password" type="password" placeholder="Enter your password" autocomplete="current-password" required /></div></label><p v-if="loginError" class="form-error" role="alert">{{loginError}}</p><button class="btn primary login-submit" type="submit">Sign In <ArrowRight :size="17"/></button></form>
      <div class="register-line">New to Kodiak? <button @click="openModal('supplier')">Create Supplier Account <ArrowUpRight :size="14"/></button></div>
      <div class="demo-divider"><span>OR EXPLORE A DEMO WORKSPACE</span></div>
      <div class="demo-roles"><button @click="demoLogin('admin')"><span class="role-icon admin"><ShieldCheck :size="20"/></span><strong>Admin</strong><small>Complete oversight</small><ArrowUpRight :size="15"/></button><button @click="demoLogin('distributor')"><span class="role-icon distributor"><Building2 :size="20"/></span><strong>Distributor</strong><small>Your supplier network</small><ArrowUpRight :size="15"/></button><button @click="demoLogin('supplier')"><span class="role-icon supplier"><Package :size="20"/></span><strong>Supplier</strong><small>Book & track</small><ArrowUpRight :size="15"/></button></div>
      <p class="demo-note">One-click access · Sample data · No real shipments</p>
    </div><footer class="login-footer"><span>© 2026 Eknixis. All rights reserved.</span><span>Built to keep you moving.</span></footer></section>
  </div>

  <div v-else class="app-shell">
    <div v-if="mobileNav" class="sidebar-overlay" @click="mobileNav=false"></div>
    <aside class="sidebar" :class="{open:mobileNav}"><a class="brand" href="#" @click.prevent="go('dashboard')"><span class="brand-mark"><Boxes :size="24"/></span><span>kodiak<span class="brand-dot">.</span></span></a><div class="workspace-label"><span class="live-dot"></span> {{isAdmin?'OPERATIONS WORKSPACE':user.role.toUpperCase()+' WORKSPACE'}}</div><p class="nav-label">WORKSPACE</p><nav><button v-for="item in navItems" :key="item.id" :class="{active:page===item.id||(page==='detail'&&item.id==='containers')}" @click="go(item.id)"><component :is="item.icon" :size="18"/><span>{{item.label}}</span><small v-if="item.count!==undefined">{{item.count}}</small></button></nav>
      <template v-if="isAdmin"><p class="nav-label management-label">MANAGEMENT</p><nav><button :class="{active:page==='locations'}" @click="go('locations')"><MapPinned :size="18"/> Location directory</button><button :class="{active:page==='blacklist'}" @click="go('blacklist')"><ShieldBan :size="18"/> Blacklist & holds <span v-if="restricted.length" class="nav-alert">{{restricted.length}}</span></button></nav></template>
      <div class="sidebar-bottom"><div class="demo-box"><span class="demo-icon"><Globe2 :size="19"/></span><strong>Your demo workspace</strong><p>Explore every step.<br>Changes save in this browser.</p><button @click="openModal('reset')"><RefreshCw :size="13"/> Reset sample data</button></div><button class="profile" @click="logout" title="Sign out and switch role"><span class="avatar">{{initials(user.name)}}</span><span><strong>{{user.name}}</strong><small>{{user.role==='admin'?'Kodiak administrator':orgName}}</small></span><LogOut :size="17"/></button></div>
    </aside>
    <div class="main-shell"><header class="topbar"><div class="breadcrumb"><button class="mobile-menu icon-btn" @click="mobileNav=true" aria-label="Open navigation"><Menu :size="22"/></button><span>Workspace</span><ChevronRight :size="14"/><strong>{{pageTitle}}</strong></div><div class="topbar-actions"><ThemeToggle v-model="theme"/><span class="demo-tag"><span></span> Demo workspace</span><span class="topbar-divider"></span><button class="notification-button icon-btn" @click="go('notifications')" aria-label="Notifications"><Bell :size="20"/><i v-if="unread"></i></button><button class="top-avatar" @click="logout" aria-label="Sign out">{{initials(user.name)}}</button></div></header>
    <main>
      <div v-if="persistenceError" class="notice red"><CircleAlert :size="18"/> Browser storage is full. Current changes may not survive a reload.</div>
      <div v-if="user.role==='supplier'&&currentSupplier?.state!=='Active'" class="notice amber"><CircleAlert :size="19"/><div><strong>{{currentSupplier?.state==='Pending'?'Your account is awaiting Kodiak approval.':'New bookings are restricted for your account.'}}</strong><p>{{currentSupplier?.state==='Pending'?'Kodiak will verify your details and confirm your distributor.':currentSupplier?.reason}} Existing tracking remains available.</p></div></div>

      <template v-if="page==='dashboard'">
        <div class="page-heading"><div><div class="eyebrow">YOUR OPERATIONS, AT A GLANCE</div><h1>{{isAdmin?'A clear view. A smoother journey.':user.role==='distributor'?'Your network, connected.':'Your cargo. Your clear view.'}}</h1><p>{{isAdmin?'Every container, partner, and milestone. All in one place.':user.role==='distributor'?'Follow your linked suppliers and the shipments that move your business.':'Register containers and stay close to every step of their journey.'}}</p></div><button v-if="canCreate" class="btn primary" @click="openModal('container')"><Plus :size="17"/> Register container</button></div>
        <div class="stats-grid"><button class="stat-card" @click="go('containers')"><div class="stat-top"><span>Total containers</span><span class="stat-icon teal"><Boxes :size="20"/></span></div><div class="stat-value">{{metrics.total.toString().padStart(2,'0')}}<span class="stat-spark"><i v-for="h in [20,32,25,39,29,42,48]" :style="{height:h+'px'}"></i></span></div><div class="stat-foot"><span class="positive">{{suppliers.length}} {{user.role==='supplier'?'supplier account':'suppliers'}}</span><span>in your workspace</span></div></button><button class="stat-card" @click="go('containers');statusFilter='In transit'"><div class="stat-top"><span>In transit</span><span class="stat-icon blue"><Ship :size="20"/></span></div><div class="stat-value">{{metrics.transit.toString().padStart(2,'0')}}<span class="stat-hint">ON THE MOVE</span></div><div class="stat-foot"><span class="status-dot blue"></span><span>Across {{routeGroups.length}} shipping routes</span></div></button><button class="stat-card" @click="go('containers');statusFilter='Delivered'"><div class="stat-top"><span>Delivered</span><span class="stat-icon green"><CircleCheck :size="20"/></span></div><div class="stat-value">{{metrics.delivered.toString().padStart(2,'0')}}<span class="stat-hint">JOURNEYS COMPLETED</span></div><div class="stat-foot"><span class="positive">Delivery confirmed</span></div></button><button class="stat-card" @click="go('containers');statusFilter='On hold'"><div class="stat-top"><span>On hold</span><span class="stat-icon amber"><CircleAlert :size="20"/></span></div><div class="stat-value">{{metrics.hold.toString().padStart(2,'0')}}<span class="stat-hint">NEEDS ATTENTION</span></div><div class="stat-foot"><span class="amber-text">{{metrics.overdue}} overdue arrival{{metrics.overdue===1?'':'s'}}</span><span>in active journeys</span></div></button></div>
        <div class="overview-middle"><section class="route-card"><div class="route-card-header"><div><div class="eyebrow light">BEYOND BORDERS</div><h2>Your world, in motion.</h2><p>{{routeGroups.length}} routes. One connected workspace.</p></div><span class="route-badge"><span class="live-dot"></span> Manually updated</span></div><svg class="world-map" viewBox="0 0 800 270" aria-label="Illustrative shipping routes; not live GPS"><defs><pattern id="dots" x="0" y="0" width="8" height="8" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.15" fill="#45616a"/></pattern><linearGradient id="routeGradient"><stop stop-color="#55d6b8"/><stop offset="1" stop-color="#91e5ce"/></linearGradient></defs><path d="M67 57L116 25 159 30 188 50 218 45 237 73 210 102 181 111 178 137 149 124 120 94 82 90ZM189 144L226 157 246 193 232 231 214 257 200 209 178 178ZM350 53L381 40 412 52 445 34 495 39 527 26 592 38 646 65 701 76 720 103 692 129 653 113 626 123 607 106 573 126 547 117 529 146 506 130 488 158 469 132 452 104 424 102 407 85 377 88 363 70ZM377 108L411 103 445 123 452 154 429 190 409 219 389 195 377 160 355 129ZM561 163L595 169 623 181 646 185 654 199 619 194 591 184ZM657 208L682 194 717 202 739 225 724 247 682 252 659 230Z" fill="url(#dots)"/><path d="M460 124Q477 65 502 139M502 139Q550 80 587 172M613 115Q590 120 587 172" fill="none" stroke="url(#routeGradient)" stroke-width="2" stroke-dasharray="5 5"/><g fill="#64d8b9"><circle cx="460" cy="124" r="5"/><circle cx="502" cy="139" r="5"/><circle cx="587" cy="172" r="5"/><circle cx="613" cy="115" r="5"/></g><g fill="#fff" font-size="11" font-family="inherit"><text x="416" y="115">Jebel Ali</text><text x="495" y="161">Mumbai</text><text x="590" y="195">Singapore</text><text x="619" y="106">Shenzhen</text></g></svg><div class="route-card-footer"><span><span class="live-dot"></span> Connected across {{data.countries.length}} countries <small>Illustrative route network</small></span><button @click="go('tracking')">Explore tracking <ArrowUpRight :size="16"/></button></div></section>
        <section class="panel distribution-panel"><div class="panel-heading"><div><h2>Shipment overview</h2><p>Current journey status</p></div><Boxes :size="19" class="muted"/></div><div class="donut-area"><div class="donut" :style="{'--progress':(metrics.total?metrics.transit/metrics.total*100:0)+'%','--delivered':(metrics.total?(metrics.transit+metrics.delivered)/metrics.total*100:0)+'%'}"><div><strong>{{metrics.total}}</strong><span>containers</span></div></div><div class="donut-legend"><div v-for="(s,i) in ['In transit','Delivered','Other stages']" :key="s"><span :class="['legend-dot',['teal','blue','gray'][i]]"></span><span>{{s}}</span><strong>{{i===0?metrics.transit:i===1?metrics.delivered:metrics.total-metrics.transit-metrics.delivered}}</strong></div></div></div><div class="panel-tip"><Clock3 :size="15"/> Based on the latest manual updates</div></section></div>
        <section v-if="user.role==='distributor'" class="panel network-strip"><div><h2>Your supplier network</h2><p>{{suppliers.length}} linked suppliers · only your network is visible</p></div><div class="supplier-chips"><button v-for="s in suppliers" @click="go('containers');supplierFilter=s.id"><span class="company-avatar">{{initials(s.name)}}</span><span>{{s.name}}<small>{{scoped.filter(c=>c.supplierId===s.id).length}} containers · {{s.state}}</small></span><ChevronRight :size="16"/></button></div></section>
        <section class="panel"><div class="panel-heading"><div><h2>Recent containers <span class="count-pill">{{scoped.length}}</span></h2><p>Your latest bookings and their progress</p></div><button class="text-btn" @click="go('containers')">View all containers <ArrowRight :size="16"/></button></div><div class="table-wrap"><table><thead><tr><th>CONTAINER / BOOKING</th><th>ROUTE</th><th>SUPPLIER</th><th>STATUS</th><th>EXPECTED ARRIVAL</th><th></th></tr></thead><tbody><tr v-for="c in scoped.slice(0,5)" :key="c.id"><td><button class="cell-link" @click="openDetail(c)"><span class="container-cell-icon"><Package :size="19"/></span><span><strong>{{c.number}}</strong><small>{{c.id}} · {{c.type}}</small></span></button></td><td><div class="table-route">{{port(c.origin).city}} <ArrowRight :size="12"/> {{port(c.destination).city}}</div><small>{{port(c.origin).code}} → {{port(c.destination).code}}</small></td><td>{{supplierName(c.supplierId)}}</td><td><span class="badge" :class="c.hold?'amber':tone(c.status)"><span></span>{{c.hold?'On hold':c.status}}</span></td><td><strong class="date-cell">{{date(c.eta)}}</strong><small v-if="isOverdue(c)" class="red-text">Overdue arrival</small><small v-else>{{c.status==='Delivered'?'Completed':'Estimated'}}</small></td><td><button class="icon-btn" @click="openDetail(c)" :aria-label="'View '+c.id"><ArrowUpRight :size="18"/></button></td></tr><tr v-if="!scoped.length"><td colspan="6" class="empty-cell">No containers yet. Your first booking will appear here.</td></tr></tbody></table></div></section>
        <div class="bottom-grid"><section class="panel"><div class="panel-heading"><div><h2>Activity feed</h2><p>The latest from your operations</p></div><span class="soft-icon"><Clock3 :size="18"/></span></div><div class="activity-list"><button v-for="e in activity" @click="openDetail(e.container)"><span class="activity-icon"><Ship v-if="e.status==='In transit'" :size="17"/><Package v-else :size="17"/></span><span><strong>{{e.container.id}} <span class="muted">· {{e.status}}</span></strong><small>{{e.location}} · {{date(e.date)}} at {{time(e.date)}}</small></span><ChevronRight :size="15"/></button><p v-if="!activity.length" class="empty-cell">No activity yet.</p></div></section><section class="panel attention-panel"><div class="panel-heading"><div><h2>Needs attention <span class="count-pill amber">{{attention.length}}</span></h2><p>A little follow-up keeps things moving</p></div><CircleAlert :size="19" class="amber-text"/></div><button v-for="c in attention.slice(0,3)" class="attention-row" @click="openDetail(c)"><span class="attention-dot"></span><span><strong>{{c.id}} · {{c.hold?'Shipment on hold':isOverdue(c)?'Expected arrival passed':'Awaiting review'}}</strong><small>{{c.hold?c.holdReason:isOverdue(c)?'Ask Kodiak for an updated arrival estimate.':'New registration ready for container allocation.'}}</small></span><ChevronRight :size="15"/></button><div v-if="!attention.length" class="empty-state compact"><CircleCheck :size="28"/><h3>Everything is on course</h3><p>No outstanding items in your workspace.</p></div></section></div>
      </template>

      <template v-else-if="page==='containers'||page==='tracking'">
        <div class="page-heading"><div><div class="eyebrow">{{page==='tracking'?'FOLLOW EVERY MILESTONE':'CONTAINER OPERATIONS'}}</div><h1>{{page==='tracking'?'Every journey, in view.':'Your containers.'}}</h1><p>{{page==='tracking'?'Open a shipment for its full timeline, route, and latest reported location.':'Manage registrations and follow your cargo from origin to destination.'}}</p></div><button v-if="canCreate" class="btn primary" @click="openModal('container')"><Plus :size="17"/> Register container</button></div>
        <div class="filter-bar"><div class="search-input"><Search :size="18"/><input v-model="search" placeholder="Search container, booking, route…" aria-label="Search containers"/></div><select v-model="statusFilter" aria-label="Filter status"><option>All statuses</option><option v-for="s in statuses">{{s}}</option><option>On hold</option></select><select v-if="user.role!=='supplier'" v-model="supplierFilter" aria-label="Filter supplier"><option value="">All suppliers</option><option v-for="s in suppliers" :value="s.id">{{s.name}}</option></select><button class="btn secondary" @click="exportCSV"><Download :size="16"/> Export</button></div>
        <div v-if="page==='tracking'" class="tracking-grid"><button v-for="c in filtered" class="tracking-card" @click="openDetail(c)"><div class="tracking-card-top"><span class="soft-icon"><Ship :size="21"/></span><span class="badge" :class="c.hold?'amber':tone(c.status)">{{c.hold?'On hold':c.status}}</span></div><h3>{{c.number}}</h3><p>{{c.id}} · {{supplierName(c.supplierId)}}</p><div class="card-route"><div><strong>{{port(c.origin).city}}</strong><small>{{port(c.origin).code}}</small></div><div class="card-route-line"><span></span><Ship :size="16"/><span></span></div><div><strong>{{port(c.destination).city}}</strong><small>{{port(c.destination).code}}</small></div></div><div class="mini-progress"><span v-for="(s,i) in statuses" :class="{done:i<=statuses.indexOf(c.status)}"></span></div><div class="tracking-card-bottom"><span>Arrival <strong>{{date(c.eta)}}</strong></span><span>View timeline <ArrowUpRight :size="15"/></span></div></button></div>
        <section v-else class="panel"><div class="panel-heading"><h2>Container register <span class="count-pill">{{filtered.length}}</span></h2><span class="muted small">Manually entered · Automatically organized</span></div><div class="table-wrap"><table><thead><tr><th>CONTAINER / BOOKING</th><th>SUPPLIER</th><th>ROUTE</th><th>STATUS</th><th>ARRIVAL</th><th>ACTIONS</th></tr></thead><tbody><tr v-for="c in filtered"><td><button class="cell-link" @click="openDetail(c)"><span class="container-cell-icon"><Package :size="19"/></span><span><strong>{{c.number}}</strong><small>{{c.id}} · {{c.type}}</small></span></button></td><td>{{supplierName(c.supplierId)}}</td><td><div class="table-route">{{port(c.origin).city}} <ArrowRight :size="12"/> {{port(c.destination).city}}</div><small>{{port(c.origin).code}} → {{port(c.destination).code}}</small></td><td><span class="badge" :class="tone(c.status)">{{c.status}}</span><span v-if="c.hold" class="badge amber">On hold</span><span v-if="c.blacklisted" class="badge red">Restricted</span></td><td>{{date(c.eta)}}<small v-if="isOverdue(c)" class="red-text">Overdue</small></td><td><div class="row-actions"><button class="icon-btn" @click="openDetail(c)" :aria-label="'View '+c.id"><Eye :size="17"/></button><button v-if="isAdmin" class="icon-btn" @click="openModal('update',c)" :aria-label="'Update '+c.id"><Pencil :size="16"/></button></div></td></tr></tbody></table></div></section>
        <div v-if="!filtered.length" class="empty-state panel"><Search :size="32"/><h3>No containers found</h3><p>Try another search or register your first container.</p><button class="btn secondary" @click="search='';statusFilter='All statuses';supplierFilter=''">Clear filters</button></div>
      </template>

      <template v-else-if="page==='detail'&&detail">
        <button class="back-link" @click="go('containers')"><ArrowLeft :size="15"/> Back to containers</button><div class="page-heading"><div><div class="eyebrow">{{detail.id}} / CONTAINER JOURNEY</div><h1>{{detail.number}} <span class="badge" :class="tone(detail.status)">{{detail.status}}</span></h1><p>{{detail.type}} <span class="text-separator">/</span> {{supplierName(detail.supplierId)}} <span class="text-separator">/</span> {{detail.cargo}}</p></div><button v-if="isAdmin" class="btn primary" @click="openModal('update',detail)"><Pencil :size="17"/> Update tracking</button></div>
        <div v-if="detail.hold" class="notice amber"><CircleAlert :size="20"/><div><strong>This shipment is on hold</strong><p>{{detail.holdReason}}</p></div></div><div v-if="detail.blacklisted" class="notice red"><ShieldBan :size="20"/><div><strong>Container restricted from future allocation</strong><p>{{detail.blacklistReason}}</p></div></div>
        <section class="journey-hero"><div class="journey-hero-top"><span><span class="live-dot"></span> {{detail.status==='Delivered'?'JOURNEY COMPLETED':'JOURNEY IN PROGRESS'}}</span><span><Clock3 :size="14"/> Manually updated · {{date(detail.events.at(-1).date)}} at {{time(detail.events.at(-1).date)}}</span></div><div class="journey-route"><div><small>ORIGIN PORT</small><h2>{{port(detail.origin).name}}</h2><p>{{port(detail.origin).city}}, {{countryName(port(detail.origin).countryId)}}</p><span>{{port(detail.origin).code}}</span></div><div class="journey-connection"><div><span class="route-end"></span><span class="dashed"></span><span class="journey-ship"><Ship :size="30"/></span><span class="dashed"></span><span class="route-end"></span></div><p>{{detail.vessel||'Vessel awaiting assignment'}}</p></div><div><small>DESTINATION PORT</small><h2>{{port(detail.destination).name}}</h2><p>{{port(detail.destination).city}}, {{countryName(port(detail.destination).countryId)}}</p><span>{{port(detail.destination).code}}</span></div></div><div class="journey-stages"><div v-for="(s,i) in statuses" :class="{complete:i<statuses.indexOf(detail.status),current:i===statuses.indexOf(detail.status)}"><span><Check v-if="i<statuses.indexOf(detail.status)" :size="13"/><span v-else>{{i+1}}</span></span><strong>{{s}}</strong></div></div></section>
        <div class="detail-grid"><section class="panel timeline-panel"><div class="panel-heading"><div><h2>Tracking timeline</h2><p>Every recorded milestone, from booking to delivery</p></div><span class="count-pill">{{detail.events.length}} events</span></div><div class="timeline"><div v-for="(e,i) in [...detail.events].reverse()" :key="e.date+i" class="timeline-item" :class="{latest:i===0}"><span class="timeline-node"><Ship v-if="e.status==='In transit'" :size="17"/><CircleCheck v-else-if="e.status==='Delivered'" :size="17"/><MapPin v-else :size="17"/></span><div class="timeline-content"><div class="timeline-title"><h3>{{e.status}} <span v-if="i===0" class="latest-tag">LATEST UPDATE</span></h3><span>{{date(e.date)}} · {{time(e.date)}}</span></div><div class="timeline-location"><MapPin :size="13"/>{{e.location}}</div><p>{{e.note}}</p><small>Recorded by {{e.by}} <span v-if="e.hold">· Hold active</span></small></div></div></div><div class="timeline-note"><ShieldCheck :size="16"/> Tracking is entered by Kodiak operations. Times shown in your local timezone.</div></section><div class="detail-side"><section class="panel"><div class="panel-heading"><h2>Shipment details</h2><Package :size="19" class="muted"/></div><dl class="detail-list"><div><dt>Booking reference</dt><dd>{{detail.id}}</dd></div><div><dt>Customer reference</dt><dd>{{detail.reference||'Not provided'}}</dd></div><div><dt>Supplier</dt><dd>{{supplierName(detail.supplierId)}}</dd></div><div><dt>Distributor</dt><dd>{{distributorName(detail.distributorId)}}</dd></div><div><dt>Container type</dt><dd>{{detail.type}}</dd></div><div><dt>Cargo weight</dt><dd>{{Number(detail.weight).toLocaleString()}} kg</dd></div><div><dt>Packages</dt><dd>{{detail.packages}}</dd></div><div><dt>Expected departure</dt><dd>{{date(detail.departure,true)}}</dd></div><div><dt>Expected arrival</dt><dd :class="{'red-text':isOverdue(detail)}">{{date(detail.eta,true)}}</dd></div></dl></section><section class="help-card"><Anchor :size="26"/><h3>People behind every milestone.</h3><p>Your Kodiak operations team maintains this journey. Suppliers and distributors have a shared, read-only view.</p><span><ShieldCheck :size="15"/> {{isAdmin?'You can update this shipment':'Tracking managed by Kodiak'}}</span></section></div></div>
      </template>

      <template v-else-if="page==='suppliers'||page==='distributors'||page==='users'">
        <div class="page-heading"><div><div class="eyebrow">YOUR CONNECTED NETWORK</div><h1>{{pageTitle}}.</h1><p>{{page==='suppliers'?'A clear view of supplier accounts, relationships, and container activity.':page==='distributors'?'The distribution partners connecting Kodiak and its suppliers.':'Create workspace access and assign each person the right role.'}}</p></div><button v-if="isAdmin" class="btn primary" @click="openModal(page==='suppliers'?'supplier':page==='distributors'?'distributor':'user')"><Plus :size="17"/> {{page==='suppliers'?'Add supplier':page==='distributors'?'Add distributor':'Create user'}}</button></div>
        <div v-if="page==='suppliers'" class="partner-grid"><article v-for="s in suppliers" class="panel partner-card"><div class="partner-top"><span class="partner-avatar">{{initials(s.name)}}</span><span class="badge" :class="tone(s.state)">{{s.state}}</span></div><h2>{{s.name}}</h2><p>{{s.category}}</p><div class="partner-meta"><span><MapPin :size="14"/>{{s.country}}</span><span><Building2 :size="14"/>{{distributorName(s.distributorId)}}</span><span><Mail :size="14"/>{{s.email}}</span></div><div class="partner-counts"><div><strong>{{scoped.filter(c=>c.supplierId===s.id).length}}</strong><small>Containers</small></div><div><strong>{{scoped.filter(c=>c.supplierId===s.id&&c.status==='In transit').length}}</strong><small>In transit</small></div><div><strong>{{scoped.filter(c=>c.supplierId===s.id&&c.status==='Delivered').length}}</strong><small>Delivered</small></div></div><div class="partner-footer"><button class="text-btn" @click="go('containers');supplierFilter=s.id">View containers <ArrowRight :size="14"/></button><button v-if="isAdmin&&s.state==='Pending'" class="btn small-btn primary" @click="openModal('approve',s)">Review</button><button v-else-if="isAdmin" class="icon-btn" @click="openModal(s.state==='Blacklisted'?'release':'restrict',s)" :aria-label="(s.state==='Blacklisted'?'Unblock ':'Blacklist ')+s.name"><ShieldBan :size="17"/></button></div></article></div>
        <div v-if="page==='distributors'&&isAdmin" class="partner-grid"><article v-for="d in data.distributors" class="panel partner-card"><div class="partner-top"><span class="partner-avatar blue-avatar"><Building2 :size="27"/></span><span class="badge green">Active</span></div><h2>{{d.name}}</h2><p>{{d.contact}} · {{d.country}}</p><div class="partner-meta"><span><Mail :size="14"/>{{d.email}}</span><span><MapPin :size="14"/>{{d.address}}</span></div><div class="partner-counts"><div><strong>{{data.suppliers.filter(s=>s.distributorId===d.id).length}}</strong><small>Suppliers</small></div><div><strong>{{data.containers.filter(c=>c.distributorId===d.id).length}}</strong><small>Containers</small></div></div><div class="linked-names"><span v-for="s in data.suppliers.filter(s=>s.distributorId===d.id)">{{s.name}}</span></div></article></div>
        <section v-if="page==='users'&&isAdmin" class="panel"><div class="panel-heading"><h2>Workspace users <span class="count-pill">{{data.users.length}}</span></h2><span class="muted small">Role-based demo access</span></div><div class="table-wrap"><table><thead><tr><th>USER</th><th>EMAIL</th><th>ROLE</th><th>ORGANIZATION</th><th>STATUS</th></tr></thead><tbody><tr v-for="u in data.users"><td><span class="user-cell"><span class="avatar light-avatar">{{initials(u.name)}}</span><strong>{{u.name}}</strong></span></td><td>{{u.email}}</td><td><span class="badge" :class="u.role==='admin'?'purple':u.role==='distributor'?'blue':'green'">{{u.role}}</span></td><td>{{u.role==='admin'?'Kodiak':u.role==='supplier'?supplierName(u.org):distributorName(u.org)}}</td><td><span class="badge green">Active</span></td></tr></tbody></table></div></section>
      </template>

      <template v-else-if="page==='locations'&&isAdmin"><div class="page-heading"><div><div class="eyebrow">YOUR GLOBAL DIRECTORY</div><h1>Locations, connected.</h1><p>Maintain the countries, states, and ports that power your shipping routes.</p></div><button class="btn primary" @click="openModal(locationTab==='ports'?'port':locationTab==='states'?'state':'country')"><Plus :size="17"/> Add {{locationTab==='countries'?'country':locationTab==='states'?'state':'port'}}</button></div><div class="tabs"><button v-for="(label,key) in {ports:'Ports',states:'States / regions',countries:'Countries'}" :class="{active:locationTab===key}" @click="locationTab=key"><MapPin v-if="key==='ports'" :size="16"/><Globe2 v-else :size="16"/>{{label}} <span>{{data[key].length}}</span></button></div><section class="panel"><div class="table-wrap"><table><thead><tr><th>{{locationTab==='ports'?'PORT NAME':locationTab==='states'?'STATE / REGION':'COUNTRY'}}</th><th v-if="locationTab!=='states'">CODE</th><th v-if="locationTab!=='countries'">COUNTRY</th><th v-if="locationTab==='ports'">STATE / REGION</th><th>STATUS</th></tr></thead><tbody><tr v-for="l in data[locationTab]"><td><strong class="location-name"><MapPin :size="16"/>{{l.name}}</strong><small v-if="l.city">{{l.city}}</small></td><td v-if="locationTab!=='states'"><span class="code-tag">{{l.code}}</span></td><td v-if="locationTab!=='countries'">{{countryName(l.countryId)}}</td><td v-if="locationTab==='ports'">{{data.states.find(s=>s.id===l.stateId)?.name}}</td><td><span class="badge green">Active</span></td></tr></tbody></table></div></section></template>

      <template v-else-if="page==='blacklist'&&isAdmin"><div class="page-heading"><div><div class="eyebrow">CONTROL & ACCOUNTABILITY</div><h1>Keep your operations protected.</h1><p>Review supplier restrictions and active container holds without losing shipment history.</p></div></div><div class="notice amber"><ShieldCheck :size="20"/><div><strong>Restrictions stop new bookings, not visibility.</strong><p>Existing shipments remain visible. Kodiak can update their physical progress and release holds independently.</p></div></div><section class="panel"><div class="panel-heading"><div><h2>Supplier restrictions</h2><p>Use the action on an active supplier to add a restriction.</p></div><span class="count-pill">{{restricted.length}} blacklisted</span></div><div class="table-wrap"><table><thead><tr><th>SUPPLIER</th><th>STATUS</th><th>REASON / RESTRICTION</th><th>ACTION</th></tr></thead><tbody><tr v-for="s in data.suppliers.filter(s=>s.state!=='Pending')"><td><strong>{{s.name}}</strong><small>{{distributorName(s.distributorId)}}</small></td><td><span class="badge" :class="tone(s.state)">{{s.state}}</span></td><td class="reason-cell">{{s.reason||'No active restrictions'}}<small v-if="s.reason">{{s.restrictedBy}} · {{date(s.restrictedAt)}}</small></td><td><button class="btn small-btn" :class="s.state==='Blacklisted'?'secondary':'danger-outline'" @click="openModal(s.state==='Blacklisted'?'release':'restrict',s)">{{s.state==='Blacklisted'?'Remove restriction':'Blacklist supplier'}}</button></td></tr></tbody></table></div></section><section class="panel section-gap"><div class="panel-heading"><div><h2>Container holds & restrictions</h2><p>Current exceptions across all journeys</p></div></div><div v-if="!scoped.some(c=>c.hold||c.blacklisted)" class="empty-cell">No container restrictions are active.</div><div v-for="c in scoped.filter(c=>c.hold||c.blacklisted)" class="restriction-row"><span class="soft-icon amber"><ShieldBan :size="20"/></span><div><strong>{{c.id}} · {{c.number}}</strong><p>{{c.hold?c.holdReason:c.blacklistReason}}</p></div><button class="btn secondary small-btn" @click="openModal('update',c)">Review <ArrowUpRight :size="14"/></button></div></section><section v-if="data.audit.length" class="panel section-gap"><div class="panel-heading"><h2>Recent audit history</h2></div><div v-for="a in data.audit.slice(0,8)" class="audit-row"><ShieldCheck :size="16"/><div><strong>{{a.action}} · {{a.entity}}</strong><small>{{a.reason}} · {{a.by}} · {{date(a.date)}} {{time(a.date)}}</small></div></div></section></template>

      <template v-else-if="page==='reports'"><div class="page-heading"><div><div class="eyebrow">FROM MOVEMENT TO INSIGHT</div><h1>The story behind your shipments.</h1><p>Three focused reports. Always based on the records in your workspace.</p></div><button class="btn primary" @click="exportCSV"><Download :size="17"/> Export report</button></div><div class="report-choices"><button v-for="r in [{id:'register',title:'Container register',desc:'Status, routes & expected arrivals',icon:Boxes},{id:'routes',title:'Route performance',desc:'Volume and completion by corridor',icon:Route},{id:'suppliers',title:'Supplier activity',desc:'Container activity by supplier',icon:Users}]" :class="{active:report===r.id}" @click="report=r.id"><component :is="r.icon" :size="23"/><span><strong>{{r.title}}</strong><small>{{r.desc}}</small></span><CircleCheck v-if="report===r.id" :size="18"/></button></div><div class="report-summary"><span><FileText :size="17"/>{{report==='register'?'Container register':report==='routes'?'Route performance':'Supplier activity'}}</span><span>All recorded dates · {{scoped.length}} journeys · {{orgName}}</span></div>
      <section class="panel"><div v-if="report==='register'" class="filter-bar report-filters"><div class="search-input"><Search :size="17"/><input v-model="search" aria-label="Search report" placeholder="Search report…"/></div><select v-model="statusFilter" aria-label="Report status"><option>All statuses</option><option v-for="s in statuses">{{s}}</option><option>On hold</option></select></div><div class="table-wrap"><table v-if="report==='register'"><thead><tr><th>BOOKING</th><th>SUPPLIER</th><th>ROUTE</th><th>STATUS</th><th>ARRIVAL</th><th>HOLD</th></tr></thead><tbody><tr v-for="c in filtered"><td><button class="text-btn" @click="openDetail(c)">{{c.id}}</button></td><td>{{supplierName(c.supplierId)}}</td><td>{{port(c.origin).code}} → {{port(c.destination).code}}</td><td><span class="badge" :class="tone(c.status)">{{c.status}}</span></td><td>{{date(c.eta,true)}}</td><td>{{c.hold?'Yes':'No'}}</td></tr></tbody></table><table v-else-if="report==='routes'"><thead><tr><th>SHIPPING CORRIDOR</th><th>TOTAL</th><th>ACTIVE</th><th>DELIVERED</th><th>ON HOLD</th><th>COMPLETION</th></tr></thead><tbody><tr v-for="r in routeGroups"><td><strong>{{port(r.origin).city}} → {{port(r.destination).city}}</strong><small>{{port(r.origin).code}} / {{port(r.destination).code}}</small></td><td>{{r.total}}</td><td>{{r.active}}</td><td>{{r.delivered}}</td><td>{{r.hold}}</td><td><div class="report-progress"><span><i :style="{width:r.delivered/r.total*100+'%'}"></i></span>{{Math.round(r.delivered/r.total*100)}}%</div></td></tr></tbody></table><table v-else><thead><tr><th>SUPPLIER</th><th>ACCOUNT</th><th>CONTAINERS</th><th>IN TRANSIT</th><th>DELIVERED</th><th>ON HOLD</th></tr></thead><tbody><tr v-for="s in suppliers"><td><strong>{{s.name}}</strong></td><td><span class="badge" :class="tone(s.state)">{{s.state}}</span></td><td>{{scoped.filter(c=>c.supplierId===s.id).length}}</td><td>{{scoped.filter(c=>c.supplierId===s.id&&c.status==='In transit').length}}</td><td>{{scoped.filter(c=>c.supplierId===s.id&&c.status==='Delivered').length}}</td><td>{{scoped.filter(c=>c.supplierId===s.id&&c.hold).length}}</td></tr></tbody></table></div><div class="panel-tip"><ShieldCheck :size="15"/> Reports and exports respect your role. All figures use manually entered demo records.</div></section></template>

      <template v-else-if="page==='notifications'"><div class="page-heading"><div><div class="eyebrow">STAY IN THE LOOP</div><h1>Your operational inbox.</h1><p>Relevant updates from your shipments and supplier accounts.</p></div><button class="btn secondary" @click="markAll"><CheckCheck :size="17"/> Mark all read</button></div><section class="panel"><button v-for="n in notifications" class="notification-row" :class="{unread:!n.readBy.includes(userId)}" @click="markRead(n)"><span class="soft-icon"><Bell :size="20"/></span><div><strong>{{n.title}}</strong><p>{{n.text}}</p><small>{{date(n.date)}} · {{time(n.date)}}</small></div><span v-if="!n.readBy.includes(userId)" class="unread-dot"></span><ChevronRight v-if="n.containerId" :size="18"/></button><div v-if="!notifications.length" class="empty-state"><Bell :size="30"/><h3>You're all caught up</h3><p>Updates to your records will appear here.</p></div></section></template>
      <footer class="app-footer"><span>© 2026 Eknixis. All rights reserved.</span><span><span class="live-dot"></span> Demo data · Saved on this device</span></footer>
    </main></div>
  </div>

  <div v-if="modal" class="modal-backdrop" @click.self="modal=''">
    <section class="modal" :class="{'wide-modal':['container','supplier','distributor','update'].includes(modal)}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-header"><div><div class="eyebrow">{{modal==='update'?'KODIAK OPERATIONS':modal==='reset'?'DEMO WORKSPACE':'LET’S KEEP THINGS MOVING'}}</div><h2 id="modal-title">{{modalTitle}}</h2></div><button class="icon-btn" @click="modal=''" aria-label="Close dialog"><X :size="22"/></button></div>
    <div v-if="modal==='reset'" class="reset-content"><p>This restores the original sample data and demo logins. Bookings, accounts, and updates created in this browser will be removed.</p><div class="modal-footer"><button class="btn secondary" @click="modal=''">Keep changes</button><button class="btn danger" @click="reset">Reset demo</button></div></div>
    <form v-else @submit.prevent="save"><div class="modal-body">
      <template v-if="modal==='container'"><div class="form-notice"><Package :size="18"/> Create a booking request. Kodiak will allocate and track your container.</div><h3 class="form-section-title">01 <span>Container & cargo</span></h3><div class="form-grid"><label v-if="isAdmin">Supplier<select v-model="form.supplierId" required><option v-for="s in data.suppliers.filter(s=>s.state==='Active')" :value="s.id">{{s.name}}</option></select></label><label>Distributor<input :value="distributorName(data.suppliers.find(s=>s.id===form.supplierId)?.distributorId)" disabled/></label><label>Container number <small>(optional)</small><input v-model="form.number" placeholder="e.g. MSCU 782341-6" maxlength="24"/></label><label>Container type<select v-model="form.type"><option>20′ Standard</option><option>40′ Standard</option><option>40′ High Cube</option><option>20′ Reefer</option><option>40′ Reefer</option></select></label><label class="full-width">Cargo description<input v-model="form.cargo" placeholder="What are you shipping?" required maxlength="180"/></label><label>Gross weight (kg)<input v-model="form.weight" type="number" min="1" max="100000" required/></label><label>Number of packages<input v-model="form.packages" type="number" min="1" max="1000000" required/></label></div><h3 class="form-section-title">02 <span>Route & schedule</span></h3><div class="form-grid"><label>Origin port<select v-model="form.origin" required><option v-for="p in data.ports" :value="p.id">{{p.name}} · {{p.code}}</option></select></label><label>Destination port<select v-model="form.destination" required><option v-for="p in data.ports" :value="p.id">{{p.name}} · {{p.code}}</option></select></label><label>Expected departure<input v-model="form.departure" type="date" required/></label><label>Expected arrival<input v-model="form.eta" type="date" :min="form.departure" required/></label><label class="full-width">Your reference <small>(optional)</small><input v-model="form.reference" placeholder="Purchase order or booking reference" maxlength="60"/></label></div></template>
      <template v-if="modal==='supplier'||modal==='distributor'"><div v-if="modal==='supplier'&&!isAdmin" class="form-notice"><ShieldCheck :size="18"/> Submit your details for Kodiak approval. Booking access follows verification.</div><h3 class="form-section-title">01 <span>Company information</span></h3><div class="form-grid"><label class="full-width">Company name<input v-model="form.name" required placeholder="Registered business name" maxlength="90"/></label><label>Contact person<input v-model="form.contact" required placeholder="Full name" maxlength="80"/></label><label>Business email<input v-model="form.email" type="email" required placeholder="contact@company.com"/></label><label>Phone number<input v-model="form.phone" type="tel" required placeholder="Include country code" maxlength="30"/></label><label>Country<select v-model="form.country"><option v-for="c in data.countries">{{c.name}}</option></select></label><label class="full-width">Address<input v-model="form.address" required placeholder="Business address" maxlength="200"/></label><label v-if="modal==='supplier'">{{isAdmin?'Assigned distributor':'Requested distributor'}}<select v-model="form.distributorId" :required="isAdmin"><option value="">Let Kodiak assign a distributor</option><option v-for="d in data.distributors" :value="d.id">{{d.name}}</option></select></label><label v-if="modal==='supplier'">Business category<select v-model="form.category"><option>General cargo</option><option>Textiles & apparel</option><option>Food & produce</option><option>Electronics</option><option>Building materials</option></select></label><label v-if="modal==='supplier'" class="full-width">{{isAdmin?'Initial password (optional — creates login)':'Create a password'}}<input v-model="form.password" type="password" minlength="8" :required="!isAdmin" autocomplete="new-password" placeholder="At least 8 characters"/><small>Demo only. Do not use a real password.</small></label></div><p v-if="modal==='distributor'" class="muted small section-gap">After creating the distributor, use User management to create its login.</p></template>
      <template v-if="modal==='user'"><div class="form-grid single"><label>Full name<input v-model="form.name" required maxlength="80"/></label><label>Email address<input v-model="form.email" type="email" required/></label><label>Role<select v-model="form.role" @change="form.org=form.role==='supplier'?data.suppliers[0]?.id:form.role==='distributor'?data.distributors[0]?.id:'kodiak'"><option value="admin">Admin</option><option value="distributor">Distributor</option><option value="supplier">Supplier</option></select></label><label v-if="form.role!=='admin'">Organization<select v-model="form.org" required><option v-for="o in form.role==='supplier'?data.suppliers:data.distributors" :value="o.id">{{o.name}}</option></select></label><label>Initial password<input v-model="form.password" type="password" required minlength="8" autocomplete="new-password"/><small>Use a demo password, not a real credential.</small></label></div></template>
      <template v-if="modal==='update'"><div class="form-notice"><ShieldCheck :size="18"/> {{form.id}} · Changes are added to the shipment timeline and audit history.</div><div class="form-grid"><label>Container number<input v-model="form.number" required maxlength="24"/></label><label>Official status<select v-model="form.status"><option v-for="s in statuses">{{s}}</option></select></label><label>Event date & time<input v-model="form.eventDate" type="datetime-local" required/></label><label>Reported location<input v-model="form.location" required maxlength="100"/></label><label>Vessel name<input v-model="form.vessel" placeholder="If applicable" maxlength="80"/></label><label>Expected arrival<input v-model="form.eta" type="date" required/></label><label class="full-width">Operational note<textarea v-model="form.note" required rows="3" placeholder="What changed? Add context for the supplier and distributor." maxlength="600"></textarea></label></div><div class="restriction-controls"><label class="checkbox-label"><input type="checkbox" v-model="form.hold"/><span><strong>Place shipment on hold</strong><small>Keep tracking visible while preventing completion.</small></span></label><label v-if="form.hold">Hold reason<textarea v-model="form.holdReason" required rows="2" maxlength="400"></textarea></label><label class="checkbox-label"><input type="checkbox" v-model="form.blacklisted"/><span><strong>Blacklist this physical container</strong><small>Flag it as restricted from future allocation.</small></span></label><label v-if="form.blacklisted">Restriction reason<textarea v-model="form.blacklistReason" required rows="2" maxlength="400"></textarea></label></div></template>
      <template v-if="['restrict','release','approve'].includes(modal)"><div class="form-notice"><Building2 :size="18"/>{{form.name}}</div><p class="muted modal-explanation">{{modal==='restrict'?'New bookings will be blocked. Existing shipments remain visible and can be managed by Kodiak.':modal==='release'?'This supplier will be able to submit new bookings again. The restriction history will be retained.':'Confirm the distributor relationship to activate this supplier and allow container bookings.'}}</p><label v-if="modal==='approve'">Assign distributor<select v-model="form.distributorId" required><option v-for="d in data.distributors" :value="d.id">{{d.name}}</option></select></label><label v-else>Reason for {{modal==='restrict'?'restriction':'release'}}<textarea v-model="form.reason" required rows="4" maxlength="500" placeholder="Add a clear operational reason…"></textarea></label></template>
      <template v-if="['country','state','port'].includes(modal)"><div class="form-grid single"><label>{{modal==='country'?'Country name':modal==='state'?'State / region name':'Port name'}}<input v-model="form.name" required maxlength="80"/></label><label v-if="modal!=='state'">{{modal==='country'?'Country code (2 letters)':'Port code (5 letters/digits)'}}<input v-model="form.code" required :pattern="modal==='country'?'[A-Za-z]{2}':'[A-Za-z]{2}[A-Za-z0-9]{3}'" :maxlength="modal==='country'?2:5" style="text-transform:uppercase"/></label><label v-if="modal!=='country'">Country<select v-model="form.countryId" @change="form.stateId=data.states.find(s=>s.countryId===form.countryId)?.id||''"><option v-for="c in data.countries" :value="c.id">{{c.name}}</option></select></label><label v-if="modal==='port'">State / region<select v-model="form.stateId" required><option value="" disabled>Select a state</option><option v-for="s in stateOptions" :value="s.id">{{s.name}}</option></select><small v-if="!stateOptions.length">Add a state for this country first.</small></label><label v-if="modal==='port'">City<input v-model="form.city" required maxlength="80"/></label></div></template>
      <p v-if="formError" class="form-error" role="alert"><CircleAlert :size="16"/>{{formError}}</p>
    </div><div class="modal-footer"><span class="form-footer-note"><LockKeyhole :size="13"/> Demo data stays in this browser</span><button class="btn secondary" type="button" @click="modal=''">Cancel</button><button class="btn" :class="modal==='restrict'?'danger':'primary'" type="submit">{{modal==='container'?'Submit registration':modal==='supplier'&&!isAdmin?'Submit application':modal==='update'?'Save tracking update':modal==='restrict'?'Blacklist supplier':modal==='release'?'Remove restriction':modal==='approve'?'Approve supplier':'Save '+modal}}<ArrowRight :size="15"/></button></div></form></section>
  </div>
  <Transition name="toast"><div v-if="toast" class="toast-message" role="status"><CircleCheck :size="19"/>{{toast}}<button @click="toast=''" aria-label="Dismiss message"><X :size="16"/></button></div></Transition>
</template>

